theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
end-of-line-diagnostics = "error"


[editor.inline-diagnostics]
cursor-line = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

