# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

includes:
  deps:
    taskfile: ./deps.yml
    flatten: true

tasks:
  alacritty:
    cmd: ./sym.sh alacritty
  fish:
    cmd: ./sym.sh fish

  hypr:
    cmd: ./sym.sh hypr
  mako:
    cmd: ./sym.sh mako
  rofi:
    cmd: ./sym.sh rofi
  waybar:
    cmd: ./sym.sh waybar
  wlogout:
    cmd: ./sym.sh wlogout
  zed:
    cmd: ./sym.sh zed

  default:
    deps: [all]
        
  all:
    deps: [alacritty, fish, hypr, mako, rofi, waybar, wlogout, zed]

  removeall:
    cmds:
      - rm ~/.config/alacritty
      - rm ~/.config/fish
      - rm ~/.config/hypr
      - rm ~/.config/mako
      - rm ~/.config/rofi
      - rm ~/.config/waybar
      - rm ~/.config/wlogout
      - rm ~/.config/zed
