# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3

includes:
  deps:
    taskfile: ./deps.yml
    flatten: true
  config:
    taskfile: ./config/Taskfile.yml
    dir: ./config

tasks:
  all:
    deps: [galias, config:all]

  purge:
    cmd: yay -Rsn $(yay -Qdtq)

  galias:
    cmds:
      - git config --global alias.co checkout
      - git config --global alias.br branch
      - git config --global alias.st status
