-- plugins
require("plugins/blankline")
require("plugins/catppuccin")
require("plugins/conform")
require("plugins/mini")
require("plugins/oil")
require("plugins/treesitter")
require("plugins/whichkey")
require("plugins/gitsigns")
require("plugins/origami")
