all:
    #!/usr/bin/env bash

    BASEDIR=$(pwd)

    function sym {
        CONF=$1
        CONF_BASE=$(basename "$CONF")
    
        echo "rm -rf ~/.config/$CONF_BASE"
        rm -rf ~/.config/$CONF_BASE

    
        echo "ln -s $BASEDIR/$CONF ~/.config/$CONF_BASE"
        ln -s $BASEDIR/$CONF ~/.config/$CONF_BASE
    }

    confs=(
        */
        starship.toml
        spotify-launcher.conf
    )

    echo "set blink-matching-paren off" > ~/.inputrc

    for i in "${confs[@]}"; do
        sym "$i"
    done

rm:
    #!/usr/bin/env bash

    confs=(
        */
        starship.toml
        spotify-launcher.conf
    )

    for i in "${confs[@]}"; do
        echo "rm -rf ~/.config/$(basename "$i")"
        rm -rf ~/.config/$(basename "$i")
    done

    rm -rf ~/.config/starship.toml
