#!/usr/bin/env python3

import os
import subprocess
import argparse

desktops = {
    "Hyprland": {
        "monitor_off": "hyprctl dispatch dpms off",
        "monitor_on": "hyprctl dispatch dpms on",
    },
    "niri": {
        "monitor_off": "niri msg action power-off-monitors",
        "monitor_on": "niri msg action power-on-monitors",
    },
    "sway": {
        "monitor_off": "swaymsg 'output * power off'",
        "monitor_on": "swaymsg 'output * power on'",
    },
}

desktop = os.environ.get("XDG_CURRENT_DESKTOP")
if desktop not in desktops:
    print("Desktop not supported")
    os._exit(0)

off = desktops[desktop]["monitor_off"]
on = desktops[desktop]["monitor_on"]
daemon = "swayidle"

command = [
    "swayidle",
    "timeout",
    "100",
    "brightnessctl -s set 5",
    "resume",
    "brightnessctl -r",
    "timeout",
    "110",
    off,
    "resume",
    on,
    "timeout",
    "120",
    "hyprlock",
    "before-sleep",
    "hyprlock",
]

now_command = [
    "swayidle",
    "timeout",
    "1",
    off,
    "resume",
    f'{on}; pkill swayidle; swayidle timeout 10 "{off}" resume "{on}"',
]


def run(cmd):
    subprocess.Popen(
        cmd,
        start_new_session=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )


def start():
    run(command)


def stop():
    run(["killall", daemon])


def toggle():
    if is_running():
        run(["killall", daemon])
    else:
        run(command)


def notify_waybar():
    run(["pkill", "-RTMIN+1", "waybar"])
    run(["pkill", "-RTMIN+1", ".waybar-wrapped"])


def is_running():
    return subprocess.run(["pidof", daemon], capture_output=True).returncode == 0


def now():
    running = is_running()

    if running:
        stop()

    subprocess.Popen(now_command)
    if subprocess.run(["pidof", "hyprlock"], capture_output=True).returncode != 0:
        subprocess.run(["hyprlock"])

    run(["pkill", "swayidle"])

    if running:
        start()


parser = argparse.ArgumentParser()
sub = parser.add_subparsers(dest="cmd", required=True)
sub.add_parser("start", help="Start the idle daemon")
sub.add_parser("stop", help="Kill the idle daemon")
sub.add_parser("toggle", help="Start if stopped, stop if running")
sub.add_parser("now", help="Trigger idle now")
sub.add_parser("running", help="Check if the idle daemon is running")

args = parser.parse_args()

if args.cmd == "start":
    start()
elif args.cmd == "stop":
    stop()
elif args.cmd == "toggle":
    toggle()
    notify_waybar()
elif args.cmd == "now":
    now()
elif args.cmd == "running":
    print("on" if is_running() else "off")
