#!/usr/bin/env python3
import subprocess


def main():
    slurp = subprocess.run(["slurp", "-d"], capture_output=True, text=True)
    if slurp.returncode != 0:
        return

    region = slurp.stdout.strip()

    grim = subprocess.run(["grim", "-g", region, "-"], capture_output=True)
    if grim.returncode != 0:
        return

    subprocess.run(["wl-copy"], input=grim.stdout)


if __name__ == "__main__":
    main()
