#!/usr/bin/env python3

import argparse
from subprocess import run


def rename_workspace(args):
    if args.name:
        run(["swaymsg", f'rename workspace to "{args.name}"'])
        return

    out = run(["rofi", "-dmenu", "-p", "New Name:"], capture_output=True, text=True)

    if out.returncode != 0:
        return

    run(["swaymsg", f'rename workspace to "{out.stdout.strip()}"'])


p = argparse.ArgumentParser()
s = p.add_subparsers(required=True)
rwork = s.add_parser(
    "rename_workspace", aliases=["rwork"], help="Rename the current workspace"
)
rwork.add_argument("name", nargs="?", default=None, help="Optional Name")
rwork.set_defaults(func=rename_workspace)

a = p.parse_args()
a.func(a)
