# Remap 
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Key binds
bind-key -n S-Left select-pane -L
bind-key -n S-Right select-pane -R
bind-key -n S-Up select-pane -U
bind-key -n S-Down select-pane -D

bind-key -n C-b choose-tree
bind-key -n C-k command-prompt

bind-key -n S-M-Left select-window -t-1
bind-key -n S-M-Right select-window -t+1

# Options to make tmux more pleasant
set -g mouse on
set -g mode-keys vi
set -g base-index 1
set-option -g history-limit 10000
set -g renumber-windows
set -g default-terminal "tmux-256color"

set -g @tmux-dotbar-right true
run ~/.config/tmux/dotbar.tmux

set -g message-style bg=black,fg=yellow
set -g status-left-length 50
